[package]
name = "metadata_fix"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0.139"
serde = { version = "1.0.218", features = ["derive"] }
kamadak-exif = "0.6.1"
png = "0.17.16"
chrono = "0.4.40"
eframe = "0.31.1"
rfd = "0.15.3"
